apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/hungtran84/argocd-example-app:~1
spec:
  project: default

  source:
    repoURL: https://github.com/hungtran84/argocd-example-app.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/staging/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
